export const playerLabels = {
  id: 'ID',
  playerName: 'Player Name',
  iplSeasonsPlayed: 'IPL Seasons Played',
  role: 'Role',
  totalRuns: 'Total Runs',
  totalWickets: 'Total Wickets',
  odiRunsS: 'ODI-RUNS-S',
  odiSrB: 'ODI-SR-B',
  odiWickets: 'ODI Wickets',
  odiSrBL: 'ODI-SR-BL',
  captaincyExp: 'Captaincy Experience',
  runsS: 'RUNS-S',
  hs: 'HS',
  average: 'Average',
  srB: 'SR-B',
  sixers: 'Sixers',
  runsC: 'RUNS-C',
  wickets: 'Wickets',
  aveBL: 'AVE-BL',
  econ: 'ECON',
  srBL: 'SR-BL',
  basePrice: 'Base Price',
  criticsRating: 'Critics Rating',
  successAssestmentInPrecent: 'Success Assestment In Percent',
};
